// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcqjvkblljpnytobbzvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjcWp2a2JsbGpwbnl0b2JienZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzUyNDYsImV4cCI6MjA2NTUxMTI0Nn0.xyd_yqT9QMFSwFlkFapfHXHagOFiRtgqc1dk91QFt1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);